name: xf_demo
description: 讯飞-语音转文字
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  crypto:
  web_socket_channel:
  mic_stream:
  permission_handler:
  flutter_ffmpeg:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
